### ISSUE TITLE
Heatmap Integration

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#16]
Integrate the heatmapping system into the existing application for use with the web service's outputted geojson.

**Comment by cpsilvia** [comment]
@sjuntiff @jcworkma and I embedded a google map into our html file, pulled coordinates from our database, and displayed the points as a heatmap using googleMaps visualization library.Our geojson coordinates are embedded in a jinja template and are displayed with the map for our output.

**Comment by wtneal** [comment]
Please commit the changes.

**Comment by cpsilvia** [comment]
commited
