### ISSUE TITLE
100% heatmaps code coverage

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#18]

**Comment by idmontie** [comment]
Are these tests supposed to test what the heatmaps look like visually?  If they are, we use Qunit for testing JavaScript and visual features.

**Comment by jcworkma** [comment]
Since we are using Google Maps heatmaps, we are going to focus on testing that the proper checks are in place to ensure that the data we submit to Google is clean and will produce a heatmap.

**Comment by jcworkma** [comment]
@sjuntiff  and @cam111  please help Chris with this

**Comment by idmontie** [comment]
What percentage is this currently at? If it is above 90%, you can close this issue.

**Comment by jcworkma** [comment]
This one is hard to judge as heatmaps is a result of geolocator and views. We will call it good.
