### ISSUE TITLE
Environment Documentation

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#26]
Pertains to docker, flask, and travis-ci

**Comment by wtneal** [comment]
What exactly about flask and travis did we want to document?

**Comment by jcworkma** [comment]
That's up to you. Whatever you think would be useful for future users/developers to know. At the very least, give a link to the documentation sources for flask and travis.

**Comment by wtneal** [comment]
Feel free to any additional information and changes, but there should be sufficient information to close this issue.
