### ISSUE TITLE
Location synonyms

### ISSUE THREAD

**Issue by idmontie** [gios-asu/text-geolocator#32]
Do we have a way of identifying synonyms with the database?

Examples:
* USA
* United States
* United States of America

**Comment by wtneal** [comment]
No

**Comment by idmontie** [comment]
The Geonames project has a table of alternate names.  See  [Geonames](http://www.geonames.org/).  See [Geonames Info](http://download.geonames.org/export/dump/readme.txt).

This will be something to implement on our end after we receive your work.
