### ISSUE TITLE
Check that the Text Geolocator is finding locations

### ISSUE THREAD

**Issue by idmontie** [gios-asu/text-geolocator#33]
I added some [test data in a separate branch](https://github.com/gios-asu/text-geolocator/tree/ivan-add-documentation/test-data).  The csv files should be useful in unit tests.  Any location marked as `1` should always be in the end result GeoJSON file.

**Comment by jcworkma** [comment]
I added tests for each of the uploaded test data files in geolocator/app/tests/test_nlp_validation.py. I tabulated the results and they can be seen in geolocator/sample-data/from-ivan/test_results.ods. We currently have a 90.73% success rate at tagging all of the locations. A few of the ones missed are questionable, so I think that number should be a little higher (like what/where is "Hothot"?). We can go over the results on Monday.
