### ISSUE TITLE
Handle Unicode or UTF-8 Character encoding

### ISSUE THREAD

**Issue by rraub** [gios-asu/text-geolocator#34]
Example: https://github.com/gios-asu/text-geolocator/blob/ivan-add-documentation/test-data/2-extracted-text/Vicca_etal_2014_Biogeosciences_0.txt

**Comment by jcworkma** [comment]
Unicode and UTF-8 encodings are now supported. There was a flag in the __init__ method of the Stanford NER Tagger where you could specify what encoding to use. I set it to 'utf-8'.
