### ISSUE TITLE
Change weighting algorithm

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#47]
Apply a hierarchical focus to the weighting algorithm.

For example, take "Phoenix, Maricopa County, Arizona, United States". Instead of incrementing the weight every time another location is found to have "Arizona" somewhere in its name, only increment the weight when another location has "Arizona" as its admin1name. Also, don't increment the weight of this "Phoenix" for matches made with other "Phoenix"s.

@idmontie does this sound right? I think I am missing something from our conversation.

**Comment by idmontie** [comment]
Yeah, I think you have it.  I'll reword it just in case:

> Given N results, with X results as with "Phoenix" as the admin1name, and Y results with "Arizona" in its name, for each Y result, only increment the X's that have "Arizona" as any of their adminNnames. 
> For each X result, only increment Y's that have "Phoenix" as any of their adminNnames (of which there should be none).

Hopefully that clarifies it.

Of course, this assumes that you will get hierarchical place names in the text.  If some one just says "Phoenix" and "Tucson" a human would be able to figure out that they are both in Arizona, but this algorithm would not.

**Comment by jcworkma** [comment]
The change has been implemented and it seems to work pretty well
