### ISSUE TITLE
Travis-ci running a docker image

### ISSUE THREAD

**Issue by rraub** [gios-asu/text-geolocator#5]
We talked about this briefly in our last meeting, before I forget here is an example of a working docker image on travis-ci https://github.com/lukecyca/travis-docker-example

**Comment by jcworkma** [comment]
The travis script executes without error now, so we are ready to work on the docker image problem

**Comment by wtneal** [comment]
We will see if I can get it working. I spent a few hours on it already with no luck. I have looked at some examples of other repos that have implemented the functionality, but none have passed there builds recently. The build stalls and times out at the moment.
