### ISSUE TITLE
Heatmap Research

### ISSUE THREAD

**Issue by jcworkma** [gios-asu/text-geolocator#9]
Research javascript heatmap open-source libraries for use in our project

**Comment by cpsilvia** [comment]
http://www.patrick-wied.at/static/heatmapjs/examples.html

http://www.patrick-wied.at/static/heatmapjs/docs.html#h337-register

**Comment by rraub** [comment]
Heatmapjs looks cool, only it seems to only support points. Not a show stopper, but you might want to figure out how to handle a polygon.

**Comment by cam111** [comment]
Ok is then would you like something more like a choropleth map style?

**Comment by cam111** [comment]
http://wrobstory.github.io/2013/04/python-maps-choropleth.html 
Could be an example it needs more detail and using the world.

**Comment by jcworkma** [comment]
Last meeting we decided to move forward with polygons on the heatmap and not "blobs". We can implement the polygons but are having trouble finding a data source to provide us with the polygon coordinates of a location.

The ability to outline a polygon of a location exists in Google Maps (try <a href="https://www.google.com/maps/place/Phoenix,+AZ/@33.6054149,-112.125051,10z/data=!3m1!4b1!4m2!3m1!1s0x872b12ed50a179cb:0x8c69c7f8354a1bac">this search for "phoenix, arizona"</a>), but the Google Maps API does not provide a method of accessing a polygon's coordinates.

We are not alone in the quest for polygon coordinates:
<ul><li><a href="http://stackoverflow.com/questions/12194046/google-maps-api-v3-how-to-get-region-border-coordinates-polyline-data">Google Maps API V3: How to get region border coordinates (polyline) data?</a></li><li><a href="http://stackoverflow.com/questions/9706484/add-search-area-outline-onto-google-maps-result">Add “Search Area” outline onto google maps result</a></li></ul>

Reading the above posts directs you to <a href="https://dev.twitter.com/rest/reference/get/geo/id/%3Aplace_id">Twitter's API</a> that gives you the ability of retrieving a "bounding box" of a searched "place". We are investigating if this is a sufficient and accurate source of polygon data.

**Comment by rraub** [comment]
We can (and should) still approximate an street address as a point, however at some size (maybe 1 square mile?) moving to a polygon would be much more useful. 

I would suggest starting with the large regions (countries, states, and cities) first and then work your way down. You could look at the [TIGER shapefile data](http://www.census.gov/geo/maps-data/data/tiger.html) for inside the US and convert it to postgis with the [shp2pgsql](http://suite.opengeo.org/4.1/dataadmin/pgGettingStarted/shp2pgsql.html) utility.  There also is [thematicmapping.org](http://thematicmapping.org/downloads/world_borders.php) that can provide world wide countries and areas.

Shape files are a pretty common format for vector data. Fair warning: pay attention to your map projection when using these utilities, chances are you're going to get data in two different projections.

The "bounding box" of a searched "place" could be a good approximate to start with, especially for computing how two regions compare (do they intersect? is one inside the other? etc)

**Comment by rraub** [comment]
Just another thought; if you knew the relative size of your locations (categorically speaking, so a city vs an street address) you could use your existing points and create a circle with a radius proportional to the size. The scope of this database isn't to accurately define the extent of a region so a circle approximation would be better than nothing.
